<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Construction_Desktop_Management_App</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Database\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\AttendanceView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\DashboardView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\LoginView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\PlantView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\PlotView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Views\SnagView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>
